import { Dimensions, StyleSheet } from "react-native";
import { Colors } from "react-native/Libraries/NewAppScreen";
import { Color, Fonts, Responsive, CommonStyles } from "../../Helper";

export const styles = StyleSheet.create({
    mainContainer :{
        flex:1,
        backgroundColor:Color.gray
    },
    headerView:{
        flexDirection:'row',
        height:50,
        backgroundColor:'pink',
        justifyContent:'space-between'   
    },
    menuView:{
        height:45,
        width:45,
        backgroundColor:Color.yellow,
        borderColor:Color.white,
        borderWidth:2,
        borderRadius:50,
        margin:3
    },
    menuImg:{
        height:'50%',
        width:'50%',
        position:'absolute',
        marginTop:13,
        marginLeft:-72
    },
    tapView :{
      width:200,
      alignItems:'center',
      justifyContent:'center',  
    },
    bellImg:{
        position:'absolute',
        height:'50%',
        width:'50%',
        marginTop:13,
        marginLeft:220
    },
    moreImg:
    {
        position:'absolute',
        height:'50%',
        width:'50%',
        marginTop:13,
        marginLeft:270
    },
    tapTxt:{
        color:Color.white
    },
    notificationTxt:{
        color:Color.yellow
    },
    notificationView:{
        height:45,
        width:45,
        backgroundColor:Color.yellow,
        borderColor:Color.white,
        borderWidth:2,
        borderRadius:50,
        marginTop:3,
        marginLeft:40
    },
    leftarrowImg:{
        position:'absolute',
        height:'70%',
        width:'50%',
        marginTop:8,
        marginLeft:180      
    },
    menuMoreView:{
        marginTop:40,
        height:50,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },
    moredownarrowImg:{
        position:'absolute',
        height:'70%',
        width:'50%',
        marginTop:45,
        marginLeft:270
    },
    burgerView:{
       marginLeft:5 
    },
    moreView:{
        marginRight:5
    },
    burgerMenuTxt:{
      color:Color.white  
    },
    sideMenuTxt:{
        color:Color.yellow
    },
    downarrowImg:{
        position:'absolute',
        height:'70%',
        marginLeft:-230,
        marginTop:46
    },
    gotView:{
        marginTop:100,
        height:30,
        width:150,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:Color.yellow,
        marginHorizontal:120,
        borderRadius:20
    },
    bottomTextView:{
        marginTop:100,
        flexDirection:'row',
        height:80,
        justifyContent:'space-between',
        marginHorizontal:20,
        marginBottom:50
        
    },
    dashView:{
        width:'25%',
        alignItems:'flex-start',
        justifyContent:'center'
    },
    bottomImgView:{
        height:50,
        //backgroundColor:'red',
        flexDirection:'row',
        justifyContent:'space-between',
        
    },
    homeView:{
        height:45,
        width:45,
        backgroundColor:Color.white,
        borderColor:Color.white,
        borderWidth:2,
        borderRadius:50,
        margin:3,
        marginLeft:15      
    },
    homeImg:{
        height:25,
        width:25,
        position:'absolute',
        marginTop:12,
        marginLeft:25,
        zIndex:1
    },
    callView:{
        height:45,
        width:45,
        backgroundColor:Color.white,
        borderColor:Color.white,
        borderWidth:2,
        borderRadius:50,
        margin:3,
        marginLeft:-5      
    },
    callImg:{
        height:25,
        width:25,
        position:'absolute',
        marginTop:12,
        marginLeft:110,
        zIndex:1
    },
    earnView:{
        height:45,
        width:45,
        backgroundColor:Color.white,
        borderColor:Color.white,
        borderWidth:2,
        borderRadius:50,
        margin:3,
        marginRight:10
    },
    earnImg:{
        height:25,
        width:25,
        position:'absolute',
        marginTop:12,
        marginLeft:200,
        zIndex:1
    },
    sosView:{
        height:45,
        width:45,
        backgroundColor:Color.white,
        borderColor:Color.white,
        borderWidth:2,
        borderRadius:50,
        margin:3, 
        marginRight:60     
    },
    sosImg:{
        height:25,
        width:25,
        position:'absolute',
        marginTop:13,
        marginLeft:295,
        zIndex:1
    },
    upHomeImg:{
        position:'absolute',
        height:'5%',
        width:'50%',
        marginTop:472,
        marginLeft:-60            
    },
    upCallImg:{
        position:'absolute',
        height:'5%',
        width:'50%',
        marginTop:472,
        marginLeft:25            
    },
    upEarnImg:{
        position:'absolute',
        height:'5%',
        width:'50%',
        marginTop:472,
        marginLeft:113            
    },
    upSosImg:{
        position:'absolute',
        height:'5%',
        width:'50%',
        marginTop:472,
        marginLeft:210            
    }

})